const AUTH_KEYS = Object.freeze({
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
});

const USER_KEYS = Object.freeze({
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
});

const PATIENT_KEYS = Object.freeze({
  GET_ALL_PATIENTS: 'GET_ALL_PATIENTS',
  GET_PATIENT_BY_ID: 'GET_PATIENT_BY_ID',
  CREATE_PATIENT: 'CREATE_PATIENT',
  UPDATE_PATIENT: 'UPDATE_PATIENT',
  DELETE_PATIENT: 'DELETE_PATIENT',
  SEARCH: 'SEARCH',
});

const APPOINTMENT_KEYS = Object.freeze({
  GET_ALL_APPOINTMENTS: 'GET_ALL_APPOINTMENTS',
  GET_APPOINTMENT_BY_ID: 'GET_APPOINTMENT_BY_ID',
  CREATE_APPOINTMENT: 'CREATE_APPOINTMENT',
  UPDATE_APPOINTMENT: 'UPDATE_APPOINTMENT',
  DELETE_APPOINTMENT: 'DELETE_APPOINTMENT',
});

const CONSULTATION_KEYS = Object.freeze({
  GET_ALL_CONSULTATIONS: 'GET_ALL_CONSULTATIONS',
  GET_CONSULTATION_BY_ID: 'GET_CONSULTATION_BY_ID',
  CREATE_CONSULTATION: 'CREATE_CONSULTATION',
  UPDATE_CONSULTATION: 'UPDATE_CONSULTATION',
  DELETE_CONSULTATION: 'DELETE_CONSULTATION',
});

const CLINIC_KEYS = Object.freeze({
  GET_ALL_CLINICS: 'GET_ALL_CLINICS',
  GET_CLINIC_BY_ID: 'GET_CLINIC_BY_ID',
  CREATE_CLINIC: 'CREATE_CLINIC',
  UPDATE_CLINIC: 'UPDATE_CLINIC',
  DELETE_CLINIC: 'DELETE_CLINIC',
});

export const QUERY_KEYS = Object.freeze({
  AUTH: AUTH_KEYS,
  USER: USER_KEYS,
  PATIENT: PATIENT_KEYS,
  APPOINTMENT: APPOINTMENT_KEYS,
  CONSULTATION: CONSULTATION_KEYS,
  CLINIC: CLINIC_KEYS,
});
