import type { AdminPageConfig } from '../types';

export const ADMIN_PAGE_CONFIG: Record<AdminPageConfig['id'], AdminPageConfig> = {
  'home': {
    id: 'home',
    title: 'Home',
    description: 'Your admin control center and quick navigation shortcuts.',
    tableTitle: 'Recent platform activity',
    tableColumns: ['Event', 'Module', 'Status', 'Timestamp'],
    metrics: [
      { label: 'Revenue (MTD)', value: '$284,900', note: '+12.4% vs last month' },
      { label: 'Open orders', value: '186', note: '24 pending approvals' },
      { label: 'Inventory health', value: '94%', note: '8 low-stock items' },
    ],
  },
  'dashboard': {
    id: 'dashboard',
    title: 'Dashboard',
    description: 'Overview of key admin metrics and recent activity.',
    tableTitle: 'Recent orders',
    tableColumns: ['Order', 'Dealer', 'Status', 'Total', 'Date'],
    metrics: [
      { label: 'Active orders', value: '82', note: '12 delayed deliveries' },
      { label: 'Inventory alerts', value: '8', note: 'Restock planned today' },
      { label: 'Pending approvals', value: '17', note: '7 high-priority requests' },
    ],
  },
  'products': {
    id: 'products',
    title: 'Products',
    description: 'Manage catalog items, variants, and lifecycle status.',
    actionLabel: 'Add product',
    tableTitle: 'Product list',
    tableColumns: ['Product', 'Brand', 'Category', 'Status', 'Updated'],
  },
  'categories': {
    id: 'categories',
    title: 'Categories',
    description: 'Organize product categories and hierarchical structure.',
    actionLabel: 'Add category',
    tableTitle: 'Category list',
    tableColumns: ['Category', 'Parent', 'Products', 'Updated'],
  },
  'brands': {
    id: 'brands',
    title: 'Brands',
    description: 'Maintain brand information and positioning.',
    actionLabel: 'Add brand',
    tableTitle: 'Brand list',
    tableColumns: ['Brand', 'Description', 'Created'],
  },
  'inventory': {
    id: 'inventory',
    title: 'Inventory',
    description: 'Track stock levels, reserved quantities, and movements.',
    actionLabel: 'Record adjustment',
    tableTitle: 'Inventory snapshot',
    tableColumns: ['SKU', 'Variant', 'Stock', 'Reserved', 'Updated'],
  },
  'orders': {
    id: 'orders',
    title: 'Orders',
    description: 'Monitor order lifecycle, payments, and delivery status.',
    actionLabel: 'Create order',
    tableTitle: 'Order list',
    tableColumns: ['Order', 'Dealer', 'Status', 'Total', 'Placed'],
  },
  'dealers': {
    id: 'dealers',
    title: 'Dealers',
    description: 'Manage dealer accounts and address records.',
    actionLabel: 'Add dealer',
    tableTitle: 'Dealer list',
    tableColumns: ['Dealer', 'Contact', 'Status', 'Created'],
  },
  'promotions': {
    id: 'promotions',
    title: 'Promotions',
    description: 'Configure discounts, coupons, and eligibility rules.',
    actionLabel: 'New promotion',
    tableTitle: 'Promotion list',
    tableColumns: ['Code', 'Type', 'Status', 'Active Dates'],
  },
  'invoices': {
    id: 'invoices',
    title: 'Invoices',
    description: 'View invoice records, totals, and statuses.',
    actionLabel: 'Generate invoice',
    tableTitle: 'Invoice list',
    tableColumns: ['Invoice', 'Order', 'Amount', 'Status', 'Issued'],
  },
  'ai-logs': {
    id: 'ai-logs',
    title: 'AI Logs',
    description: 'Review AI call summaries, statuses, and transcripts.',
    tableTitle: 'AI call history',
    tableColumns: ['Dealer', 'Status', 'Summary', 'Duration', 'Created'],
  },
  'settings': {
    id: 'settings',
    title: 'Settings',
    description: 'Configure admin preferences and platform defaults.',
    tableTitle: 'Settings overview',
    tableColumns: ['Section', 'Status', 'Last Updated'],
    tableRows: 4,
  },
};
